FROM ubuntu:latest as build

RUN apt-get update
RUN apt-get install openjdk-21-jdk -y
COPY . .

RUN apt-get install maven -y
RUN mvn clean install

FROM openjdk:21-jdk-slim

EXPOSE 8080

RUN ls .
COPY --from=build target/todo-list-0.0.1-SNAPSHOT.jar app.jar

ENTRYPOINT [ "java", "-jar", "-Dspring.profiles.active=$SPRING_PROFILES_ACTIVE", "app.jar" ]